/*
 * gameOfThrone.h
 *
 *  Created on: 12 nov. 2016
 *      Author: furlings
 */

#ifndef MUSIC_H_
#define MUSIC_H_

#include "song.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
// My Music
//
/////////////////////////////////////////////////////////////////////////////////////////////////////////////


float GameOfThrone[] =
  {
    E2, QUARTER, A, DOTTED_EIGHTH, C2, EIGHTH, D2, EIGHTH, E2, QUARTER, A, DOTTED_EIGHTH, C2, EIGHTH, D2, EIGHTH, E2, QUARTER, A, DOTTED_EIGHTH, C2, EIGHTH, D2, EIGHTH,
    E2, QUARTER, A, DOTTED_EIGHTH, C2S, EIGHTH, D2, EIGHTH, E2, QUARTER, A, DOTTED_EIGHTH, C2S, EIGHTH, D2, EIGHTH, E2, QUARTER, A, DOTTED_EIGHTH, C2S, EIGHTH, D2, EIGHTH,
    E2, QUARTER, A, DOTTED_EIGHTH, C2S, EIGHTH, D2, EIGHTH, E2, QUARTER, A, DOTTED_EIGHTH, A, DOTTED_EIGHTH,
    E2, HALF, A, HALF, C2, EIGHTH, D2, EIGHTH, E2, HALF, A, HALF, C2, EIGHTH, D2, EIGHTH, B, QUARTER,
    E, DOTTED_EIGHTH, G, EIGHTH, A, EIGHTH, B, QUARTER, E, DOTTED_EIGHTH, G, EIGHTH, A, EIGHTH, B, QUARTER, E, DOTTED_EIGHTH, G, EIGHTH, A, EIGHTH,
    B, QUARTER, E, DOTTED_EIGHTH, G, EIGHTH, A, EIGHTH, B, QUARTER, E, DOTTED_EIGHTH, E, DOTTED_EIGHTH,
    D2, HALF, G, HALF, C2, EIGHTH, B, EIGHTH, D2, HALF, G, HALF, C2, EIGHTH, B, EIGHTH, A, QUARTER,
    E, DOTTED_EIGHTH, F, EIGHTH, G, EIGHTH, A, QUARTER, E, DOTTED_EIGHTH, F, EIGHTH, G, EIGHTH, A, QUARTER, E, DOTTED_EIGHTH, F, EIGHTH, G, EIGHTH,
    A, QUARTER, E, DOTTED_EIGHTH, F, EIGHTH, G, EIGHTH, A, QUARTER, E, DOTTED_EIGHTH, E, DOTTED_EIGHTH,
    A, WHOLE, G, EIGHTH, A, EIGHTH, G, WHOLE, C, WHOLE, F, WHOLE, E, EIGHTH, F, EIGHTH, E, DOUBLE_WHOLE,
    F_2, WHOLE, C, WHOLE, D, WHOLE, E, DOUBLE_WHOLE,
    A, WHOLE, G, EIGHTH, A, EIGHTH, G, WHOLE, C, WHOLE, F, WHOLE, E, EIGHTH, F, EIGHTH, E, DOUBLE_WHOLE,
    F_2, WHOLE, C, WHOLE, B, WHOLE,
    E, QUARTER, A_2, DOTTED_EIGHTH, C, EIGHTH, D, EIGHTH,
    E, QUARTER, A_2, DOTTED_EIGHTH, C, EIGHTH, D, EIGHTH, E, WHOLE, REST,ETERNITY
  };

float mario[] =
  {
    E2,EIGHTH, E2,QUARTER, E2,EIGHTH, REST,EIGHTH, C2,EIGHTH, E2,QUARTER, G2,HALF, G,HALF,
    C2,DOTTED_QUARTER, G,EIGHTH, REST,QUARTER, E,QUARTER, REST,EIGHTH, A2P,QUARTER, B2,EIGHTH, REST,EIGHTH, A2S,EIGHTH, A2P,QUARTER,
    G,DOTTED_EIGHTH, E2,DOTTED_EIGHTH, G2,EIGHTH, A3P,QUARTER, F2,EIGHTH, G2,EIGHTH, REST,EIGHTH, E2,QUARTER, C2,EIGHTH, D2,EIGHTH, B2,DOTTED_QUARTER,
    C2,DOTTED_QUARTER, G,EIGHTH, REST,QUARTER, E,QUARTER, REST,EIGHTH, A2P,QUARTER, B2,EIGHTH, REST,EIGHTH, A2S,EIGHTH, A2P,QUARTER,
    G,DOTTED_EIGHTH, E2,DOTTED_EIGHTH, G2,EIGHTH, A3P,QUARTER, F2,EIGHTH, G2,EIGHTH, REST,EIGHTH, E2,QUARTER, C2,EIGHTH, D2,EIGHTH, B2,DOTTED_QUARTER,
    REST,QUARTER, G2,EIGHTH, F2S,EIGHTH, F2,EIGHTH, D2S,QUARTER, E2,EIGHTH, REST,EIGHTH, GS,EIGHTH, A2P,EIGHTH, C2,EIGHTH, REST,EIGHTH, A2P,EIGHTH, C2,EIGHTH, D2,EIGHTH,
    REST,QUARTER, G2,EIGHTH, F2S,EIGHTH, F2,EIGHTH, D2S,QUARTER, E2,EIGHTH, REST,EIGHTH, C3,QUARTER, C3,EIGHTH, C3,HALF,
    REST,QUARTER, G2,EIGHTH, F2S,EIGHTH, F2,EIGHTH, D2S,QUARTER, E2,EIGHTH, REST,EIGHTH, GS,EIGHTH, A2P,EIGHTH, C2,EIGHTH, REST,EIGHTH, A2P,EIGHTH, C2,EIGHTH, D2,EIGHTH,
    REST,QUARTER, D2S,QUARTER, REST,EIGHTH, D2,DOTTED_QUARTER, C2,HALF, REST,HALF,
    C2,EIGHTH, C2,QUARTER, C2,EIGHTH, REST,EIGHTH, C2,EIGHTH, D2,QUARTER, E2,EIGHTH, C2,QUARTER, A2P,EIGHTH, G,HALF,
    C2,EIGHTH, C2,QUARTER, C2,EIGHTH, REST,EIGHTH, C2,EIGHTH, D2,EIGHTH, E2,EIGHTH, REST,WHOLE,
    C2,EIGHTH, C2,QUARTER, C2,EIGHTH, REST,EIGHTH, C2,EIGHTH, D2,QUARTER, E2,EIGHTH, C2,QUARTER, A2P,EIGHTH, G,HALF,
    E2,EIGHTH, E2,QUARTER, E2,EIGHTH, REST,EIGHTH, C2,EIGHTH, E2,QUARTER, G2,QUARTER, REST, HALF,
    REST,ETERNITY
};


float* songs[] =
{
    GameOfThrone,
    mario
};

#endif /* MUSIC_H_ */
